# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Build node list

on:
  schedule:
    - cron: '0/30 * * * *'
  push:
    branches: [ "main" ]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    name: Fetch and choose nodes
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build list
        run: npm start
#      - uses: actions/checkout@v3
      - name: push to origin
        if: success() || failure()
        run: |
          date > generation-date.txt
          git remote set-url --push origin https://HoseanRC:$GITHUB_TOKEN@github.com/HoseanRC/v2subs.git
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add .
          git commit -m "[`date`] updated ${{ env.nodescount }} nodes"
          git push
